# Database
POSTGRESQL_USERNAME: brandon
POSTGRESQL_PASSWORD: password
POSTGRESQL_HOST: 127.0.0.1
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: pet_well

#Server
CONTAINER_PORT: 9090
ACTIVE_PROFILE: dev

#JWT
SECRET_KEY: a86e7e2786d280e6b5b1f75776dff7e8a18a41cf989304cb5fb0e58522eaadca
EXPIRY_DURATION: 3600

